import "./style.css";

function createContactTab() {
  const tabBackground = document.querySelector(".tabs");
  tabBackground.classList = "tabs contact-tab";
  tabBackground.setAttribute("data-tab", "contact");
  const contactDivContent = document.createElement("div");
  contactDivContent.className = "tab-content";
  const contactHeading = document.createElement("h2");
  contactHeading.textContent = "Get in Touch!";
  const contactBlurb = document.createElement("p");
  contactBlurb.textContent =
    "We love hearing from our customers. If you love our food or have any feedback, drop us a line. We'll do our best to respond to any concerns you may have, but due to a high volume of email we may not be able to respond to every comment. Thanks, and enjoy your next farm-fresh meal!";
  const requiredFieldsDiv = document.createElement("div");
  requiredFieldsDiv.className = "req";
  const requiredFieldsText = document.createElement("p");
  requiredFieldsText.textContent = "Required Fileds are Marked with *";
  const contactForm = document.createElement("form");
  contactForm.action = "#";
  contactForm.method = "POST";
  const firstNameLabel = document.createElement("label");
  firstNameLabel.for = "fname";
  firstNameLabel.textContent = "*First Name:";
  const firstNameInput = document.createElement("input");
  firstNameInput.type = "text";
  firstNameInput.id = "fname";
  firstNameInput.name = "firstname";
  firstNameInput.placeholder = "Your First Name";
  firstNameInput.required = true;
  const lastNameLabel = document.createElement("label");
  lastNameLabel.for = "lname";
  lastNameLabel.textContent = "*Last Name:";
  const lastNameInput = document.createElement("input");
  lastNameInput.type = "text";
  lastNameInput.id = "lname";
  lastNameInput.name = "lastname";
  lastNameInput.placeholder = "Your Last Name";
  lastNameInput.required = true;
  const emailLabel = document.createElement("label");
  emailLabel.for = "email";
  emailLabel.textContent = "*Email Address:";
  const emailInput = document.createElement("input");
  emailInput.type = "email";
  emailInput.id = "email";
  emailInput.name = "email-address";
  emailInput.placeholder = "Your Email";
  emailInput.required = true;
  const subject = document.createElement("label");
  subject.for = "subject";
  subject.textContent = "*Subject:";
  const subjectTextBox = document.createElement("textarea");
  subjectTextBox.id = "subject";
  subjectTextBox.name = "subject";
  subjectTextBox.placeholder = "Your message here";
  subjectTextBox.required = true;
  const btnInput = document.createElement("input");
  btnInput.className = "tab-btn pretend";
  btnInput.setAttribute("data-for-tab", "pretend");
  btnInput.value = "Submit";

  tabBackground.appendChild(contactDivContent);
  contactDivContent.appendChild(contactHeading);
  contactDivContent.appendChild(contactBlurb);
  contactDivContent.appendChild(requiredFieldsDiv);
  requiredFieldsDiv.appendChild(requiredFieldsText);
  contactDivContent.appendChild(contactForm);
  contactForm.appendChild(firstNameLabel);
  contactForm.appendChild(firstNameInput);
  contactForm.appendChild(lastNameLabel);
  contactForm.appendChild(lastNameInput);
  contactForm.appendChild(emailLabel);
  contactForm.appendChild(emailInput);
  contactForm.appendChild(subject);
  subject.appendChild(subjectTextBox);
  contactForm.appendChild(btnInput);
}

export default { createContactTab };
