import "./style.css";

function createReservationsTab() {
  const tabBackground = document.querySelector(".tabs");
  tabBackground.classList = "tabs reserve-tab";
  tabBackground.setAttribute("data-tab", "reserve");
  const reserveDivContent = document.createElement("div");
  reserveDivContent.className = "tab-content";
  const reserveHeading = document.createElement("h2");
  reserveHeading.textContent = "Table Reservations";
  const requiredFieldsDiv = document.createElement("div");
  requiredFieldsDiv.className = "req";
  const requiredFieldsText = document.createElement("p");
  requiredFieldsText.textContent = "Required Fileds are Marked with *";
  const reservationForm = document.createElement("form");
  reservationForm.action = "#";
  reservationForm.method = "POST";
  const nameLabel = document.createElement("label");
  nameLabel.for = "name";
  nameLabel.textContent = "*Full Name:";
  const nameInput = document.createElement("input");
  nameInput.type = "text";
  nameInput.id = "name";
  nameInput.placeholder = "Your Full Name";
  nameInput.required = true;
  const emailLabel = document.createElement("label");
  emailLabel.for = "email";
  emailLabel.textContent = "*Your Email:";
  const emailInput = document.createElement("input");
  emailInput.type = "email";
  emailInput.id = "email";
  emailInput.placeholder = "Your Email";
  emailInput.required = true;
  const phoneLabel = document.createElement("label");
  phoneLabel.for = "phone";
  phoneLabel.textContent = "*Your Phone Number:";
  const phoneInput = document.createElement("input");
  phoneInput.type = "tel";
  phoneInput.id = "phone";
  phoneInput.placeholder = "Your Phone Number";
  phoneInput.required = true;
  const dateDiv = document.createElement("div");
  dateDiv.className = "date-div";
  const dateLabel = document.createElement("label");
  dateLabel.for = "date";
  dateLabel.textContent = "*Date:";
  const dateInput = document.createElement("input");
  dateInput.type = "date";
  dateInput.id = "date";
  dateInput.name = "date";
  dateInput.required = true;
  const timeDiv = document.createElement("div");
  timeDiv.className = "time-div";
  const timeLabel = document.createElement("label");
  timeLabel.for = "time";
  timeLabel.textContent = "*Time:";
  const timeInput = document.createElement("input");
  timeInput.type = "time";
  timeInput.id = "time";
  timeInput.name = "time";
  timeInput.required = true;
  const guestsDiv = document.createElement("div");
  guestsDiv.className = "guest-div";
  const guestsLabel = document.createElement("label");
  guestsLabel.for = "guests";
  guestsLabel.textContent = "*Number of Guests:";
  const guestsInput = document.createElement("input");
  guestsInput.type = "number";
  guestsInput.id = "guests";
  guestsInput.name = "guests";
  guestsInput.min = "1";
  guestsInput.required = true;
  const requests = document.createElement("label");
  requests.for = "special-requests";
  requests.textContent = "Special Requests:";
  const requestsTextBox = document.createElement("textarea");
  requestsTextBox.id = "special-requests";
  requestsTextBox.name = "special-requests";
  const btnInput = document.createElement("input");
  btnInput.className = "tab-btn pretend";
  btnInput.setAttribute("data-for-taab", "pretend");
  btnInput.value = "Submit";

  tabBackground.appendChild(reserveDivContent);
  reserveDivContent.appendChild(reserveHeading);
  reserveDivContent.appendChild(requiredFieldsDiv);
  requiredFieldsDiv.appendChild(requiredFieldsText);
  reserveDivContent.appendChild(reservationForm);
  reservationForm.appendChild(nameLabel);
  reservationForm.appendChild(nameInput);
  reservationForm.appendChild(emailLabel);
  reservationForm.appendChild(emailInput);
  reservationForm.appendChild(phoneLabel);
  reservationForm.appendChild(phoneInput);
  reservationForm.appendChild(dateDiv);
  dateDiv.appendChild(dateLabel);
  dateDiv.appendChild(dateInput);
  reservationForm.appendChild(timeDiv);
  timeDiv.appendChild(timeLabel);
  timeDiv.appendChild(timeInput);
  reservationForm.appendChild(guestsDiv);
  guestsDiv.appendChild(guestsLabel);
  guestsDiv.appendChild(guestsInput);
  reservationForm.appendChild(requests);
  requests.appendChild(requestsTextBox);
  reservationForm.appendChild(btnInput);
}

createReservationsTab();
